### PR TITLE
Ensure MONGODB-CR is used as auth mechanism

### PR DESCRIPTION
**Pull request by sommestad**
Resolves issues with mongoose/mongodb-native where DEFAULT auth mechanism couldn't be used in reused connections.

Issue: https://github.com/LearnBoost/mongoose/issues/2619

### CODE REVIEW

**Comment by Skoog** [comment]
No acceptance tests?

**Comment by sommestad** [comment]
NO

**Comment by Skoog** [comment]
Then how do we know this solves it?

**Comment by sommestad** [comment]
Because I've tested it and Compose says so. The issue can't be reproduced in a localhost environment.

**Comment by Skoog** [comment]
I still think there should be a test reproducing the issue

**Comment by sommestad** [comment]
It's impossible without an actual DB connection and this module doesn't have one in its tests, nor can it have one without us exposing its credentials to the internet.

**Comment by sommestad** [comment]
And that's not gonna happen.

**Comment by Skoog** [comment]
So that means that we can't be 100% sure this fixes it

**Comment by sommestad** [comment]
We can be 100% certain that it doesn't work as it is now and that it's blocking ALL of our other repositories. Stop being a dick.

**Comment by Skoog** [comment]
I'm not being a dick, I'm only enforcing something YOU always nag about

**Comment by sommestad** [comment]
It's impossible to test it in this case; it's not in the other cases. Be realistic.

**Pull request merged**
